odd_visualizer_node:
  ros__parameters:
    color_configs:
      # The copyright of color configuration is owned by TUM(in case there exists such thing)
      # All the color configurations are downloaded from:
      # https://gist.github.com/lnksz/51e3566af2df5c7aa678cd4dfc8305f7
      # If you are using VSCode, installing the extension "Color Highlight"(naumovs.color-highlight)
      # could help with knowing what color will be showing in advance
      rgb_tum_blue: [17, 69, 132]
      rgb_tum_red: [153, 20, 0]
      rgb_tum_green: [159, 186, 54]

