#include "geometry_msgs/msg/polygon.hpp"


module scenery_msgs {
    module msg {
        module LaneType_Constants {
            const uint8 ROADLANE = 0;
            const uint8 CROSSWALKLANE = 1;

        };
        struct LanePrimitive {
            int64 laneID;
            uint8 laneType;
            string laneDirection;
            geometry_msgs::msg::Polygon lanePolygon;
        };
    };
};