#include "std_msgs/msg/Header.idl"

module scenery_msgs {
    module msg {
        module LaneType_Constants {
            const uint8 EMERGENCYSTREET =0;
            const uint8 BICYCLELANE =1;
            const uint8 WALKWAY =2;
            const uint8 SHAREDWALKWAY =3;
            const uint8 CROSSWALK =4;
        };
        struct nonDrivableLane {
            uint8 laneType;
        };
    };
};