#include "std_msgs/msg/Header.idl"
#include "scenery_msgs/msg/nonDrivableLane.idl"
#include "scenery_msgs/msg/edge.idl"
#include "scenery_msgs/msg/laneletODD.idl"
module scenery_msgs {
    module msg {
        struct ODDElements {
            sequence<scenery_msgs::msg::laneletODD> laneletInfo;
        };
    };
};